"""
Train a tiny CNN on MNIST and export weights to a JS file (web/model.js)
for pure-JS in-browser inference. No external JS ML library needed.

Model (~9k params):
  input 1x28x28
  conv1: 1->8, 3x3, pad1 -> relu -> maxpool2  => 8x14x14
  conv2: 8->16, 3x3, pad1 -> relu -> maxpool2 => 16x7x7
  flatten(784) -> fc 784->10
"""
import base64
import json
import os

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_JS = os.path.join(HERE, "..", "docs", "model.js")
DATA_DIR = os.path.join(HERE, "data")


class TinyCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, 3, padding=1)
        self.conv2 = nn.Conv2d(8, 16, 3, padding=1)
        self.fc = nn.Linear(16 * 7 * 7, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.flatten(1)
        return self.fc(x)


class RandomThickness:
    """Randomly thicken (dilate) or thin (erode) strokes so the model
    generalizes to thick finger-drawn touch strokes, not just MNIST pen."""

    def __call__(self, t):  # t: 1x28x28 tensor in [0,1]
        r = torch.rand(1).item()
        if r < 0.4:  # dilate (thicker)
            t = F.max_pool2d(t.unsqueeze(0), 3, stride=1, padding=1).squeeze(0)
        elif r < 0.55:  # erode (thinner)
            t = -F.max_pool2d(-t.unsqueeze(0), 3, stride=1, padding=1).squeeze(0)
        return t


def main():
    torch.manual_seed(0)
    train_tf = transforms.Compose([
        transforms.RandomAffine(degrees=12, translate=(0.1, 0.1), scale=(0.8, 1.15)),
        transforms.ToTensor(),
        RandomThickness(),
    ])
    test_tf = transforms.ToTensor()

    train_ds = datasets.MNIST(DATA_DIR, train=True, download=True, transform=train_tf)
    test_ds = datasets.MNIST(DATA_DIR, train=False, download=True, transform=test_tf)
    train_dl = DataLoader(train_ds, batch_size=128, shuffle=True, num_workers=2)
    test_dl = DataLoader(test_ds, batch_size=512, shuffle=False, num_workers=2)

    model = TinyCNN()
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)
    epochs = 4

    for ep in range(epochs):
        model.train()
        for i, (x, y) in enumerate(train_dl):
            opt.zero_grad()
            loss = F.cross_entropy(model(x), y)
            loss.backward()
            opt.step()
            if i % 100 == 0:
                print(f"epoch {ep} step {i}/{len(train_dl)} loss {loss.item():.3f}", flush=True)

        # eval
        model.eval()
        correct = 0
        with torch.no_grad():
            for x, y in test_dl:
                correct += (model(x).argmax(1) == y).sum().item()
        acc = correct / len(test_ds)
        print(f"== epoch {ep} test acc {acc:.4f}", flush=True)

    export(model)
    print(f"wrote {OUT_JS}")


def b64(t):
    return base64.b64encode(t.detach().cpu().float().contiguous().numpy().tobytes()).decode()


def export(model):
    sd = model.state_dict()
    params = {}
    for k, v in sd.items():
        params[k] = {"shape": list(v.shape), "b64": b64(v)}
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, "w") as f:
        f.write("// Auto-generated by train/train.py — tiny MNIST CNN weights.\n")
        f.write("// Float32 little-endian arrays, base64-encoded.\n")
        f.write("export const MODEL = ")
        json.dump(params, f)
        f.write(";\n")


if __name__ == "__main__":
    main()
